#!/bin/sh
PERL5LIB=$LAMBDA_TASK_ROOT/lib/perl
PERL5LIB=\
/opt/lib/perl5:\
/opt/lib/perl5/vendor_perl:\
/opt/lib/perl5/auto:\
/opt/lib/perl5/vendor_perl/auto:\
/opt/lib/perl5/x86_64:\
/opt/lib/perl5/x86_64/auto:\
/opt/lib64/perl5:\
/opt/lib64/perl5/vendor_perl:\
/opt/lib64/perl5/auto:\
/opt/lib64/perl5/vendor_perl/auto:\
/opt/lib64/perl5/x86_64:\
/opt/lib64/perl5/x86_64/auto
PATH=$LAMBDA_TASK_ROOT/bin:/opt/bin:$PATH
LANG=C
LD_LIBRARY_PATH=
export PERL5LIB PATH LANG LD_LIBRARY_PATH
exec /opt/lib64/ld-2.28.so /opt/bin/perl /opt/bootstrap.lambda.pl
